# Development
url = https://ws1.czebox.cz/DS/

# Production
# url = https://ws1.datovka.gov.cz/DS/

# Credentials
login =
password = 

# Optional path to additional certificates, may not exist.
certificates = ./certificates

# Output location
output.messages = ./output
output.attachments = ./output

# The adapter requests messages from NOW - download_interval_in_minutes to NOW.
download_interval_in_minutes = 1440
