# Development
url = https://ws1.czebox.cz/DS/
# Production
# url = https://ws1.mojedatovaschranka.cz/DS/

# Credentials
login =
password =

# Path to certificates
certificates = ./certificates

# Output location
output.messages = ./output
output.attachments = ./output

# The adapter requests messages from NOW - download_interval_in_minutes to NOW.
download_interval_in_minutes = 1440
