
package cz.czechpoint.isds.v20;

import java.math.BigInteger;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Holder;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * Eclipse Metro/3.0.2 (RELEASE-3.0.2-4d220c5; 2021-08-02T05:18:16+0000) JAXWS-RI/3.0.2 JAXWS-API/3.0.1 JAXB-RI/3.0.2 JAXB-API/${jaxb-api.version}
 * Generated source version: 3.0
 * 
 */
@WebService(name = "dmInfoPortType", targetNamespace = "http://isds.czechpoint.cz/v20")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DmInfoPortType {


    /**
     * 
     * @param dmHash
     * @param dmStatus
     * @param dmID
     */
    @WebMethod(operationName = "VerifyMessage")
    @RequestWrapper(localName = "VerifyMessage", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TIDMessInput")
    @ResponseWrapper(localName = "VerifyMessageResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TMessageVerifyOutput")
    public void verifyMessage(
        @WebParam(name = "dmID", targetNamespace = "http://isds.czechpoint.cz/v20")
        String dmID,
        @WebParam(name = "dmHash", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<THash> dmHash,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

    /**
     * 
     * @param dmReturnedMessageEnvelope
     * @param dmStatus
     * @param dmID
     */
    @WebMethod(operationName = "MessageEnvelopeDownload")
    @RequestWrapper(localName = "MessageEnvelopeDownload", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TIDMessInput")
    @ResponseWrapper(localName = "MessageEnvelopeDownloadResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TMessEnvelDownOutput")
    public void messageEnvelopeDownload(
        @WebParam(name = "dmID", targetNamespace = "http://isds.czechpoint.cz/v20")
        String dmID,
        @WebParam(name = "dmReturnedMessageEnvelope", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TReturnedMessageEnvelope> dmReturnedMessageEnvelope,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

    /**
     * 
     * @param dmID
     * @return
     *     returns cz.czechpoint.isds.v20.TStatus
     */
    @WebMethod(operationName = "MarkMessageAsDownloaded")
    @WebResult(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20")
    @RequestWrapper(localName = "MarkMessageAsDownloaded", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TIDMessInput")
    @ResponseWrapper(localName = "MarkMessageAsDownloadedResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TMarkMessOutput")
    public TStatus markMessageAsDownloaded(
        @WebParam(name = "dmID", targetNamespace = "http://isds.czechpoint.cz/v20")
        String dmID);

    /**
     * 
     * @param dmStatus
     * @param dmID
     * @param dmDelivery
     */
    @WebMethod(operationName = "GetDeliveryInfo")
    @RequestWrapper(localName = "GetDeliveryInfo", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TIDMessInput")
    @ResponseWrapper(localName = "GetDeliveryInfoResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TDeliveryMessageOutput")
    public void getDeliveryInfo(
        @WebParam(name = "dmID", targetNamespace = "http://isds.czechpoint.cz/v20")
        String dmID,
        @WebParam(name = "dmDelivery", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TDelivery> dmDelivery,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

    /**
     * 
     * @param dmStatus
     * @param dmSignature
     * @param dmID
     */
    @WebMethod(operationName = "GetSignedDeliveryInfo")
    @RequestWrapper(localName = "GetSignedDeliveryInfo", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TIDMessInput")
    @ResponseWrapper(localName = "GetSignedDeliveryInfoResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TSignDelivMessOutput")
    public void getSignedDeliveryInfo(
        @WebParam(name = "dmID", targetNamespace = "http://isds.czechpoint.cz/v20")
        String dmID,
        @WebParam(name = "dmSignature", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<byte[]> dmSignature,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

    /**
     * 
     * @param dmRecords
     * @param dmStatusFilter
     * @param dmStatus
     * @param dmOffset
     * @param dmToTime
     * @param dmSenderOrgUnitNum
     * @param dmFromTime
     * @param dmLimit
     */
    @WebMethod(operationName = "GetListOfSentMessages")
    @RequestWrapper(localName = "GetListOfSentMessages", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TListOfSentInput")
    @ResponseWrapper(localName = "GetListOfSentMessagesResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TListOfMessOutput")
    public void getListOfSentMessages(
        @WebParam(name = "dmFromTime", targetNamespace = "http://isds.czechpoint.cz/v20")
        XMLGregorianCalendar dmFromTime,
        @WebParam(name = "dmToTime", targetNamespace = "http://isds.czechpoint.cz/v20")
        XMLGregorianCalendar dmToTime,
        @WebParam(name = "dmSenderOrgUnitNum", targetNamespace = "http://isds.czechpoint.cz/v20")
        BigInteger dmSenderOrgUnitNum,
        @WebParam(name = "dmStatusFilter", targetNamespace = "http://isds.czechpoint.cz/v20")
        String dmStatusFilter,
        @WebParam(name = "dmOffset", targetNamespace = "http://isds.czechpoint.cz/v20")
        BigInteger dmOffset,
        @WebParam(name = "dmLimit", targetNamespace = "http://isds.czechpoint.cz/v20")
        BigInteger dmLimit,
        @WebParam(name = "dmRecords", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TRecordsArray> dmRecords,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

    /**
     * 
     * @param dmRecords
     * @param dmRecipientOrgUnitNum
     * @param dmStatusFilter
     * @param dmStatus
     * @param dmOffset
     * @param dmToTime
     * @param dmFromTime
     * @param dmLimit
     */
    @WebMethod(operationName = "GetListOfReceivedMessages")
    @RequestWrapper(localName = "GetListOfReceivedMessages", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TListOfFReceivedInput")
    @ResponseWrapper(localName = "GetListOfReceivedMessagesResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TListOfMessOutput")
    public void getListOfReceivedMessages(
        @WebParam(name = "dmFromTime", targetNamespace = "http://isds.czechpoint.cz/v20")
        XMLGregorianCalendar dmFromTime,
        @WebParam(name = "dmToTime", targetNamespace = "http://isds.czechpoint.cz/v20")
        XMLGregorianCalendar dmToTime,
        @WebParam(name = "dmRecipientOrgUnitNum", targetNamespace = "http://isds.czechpoint.cz/v20")
        BigInteger dmRecipientOrgUnitNum,
        @WebParam(name = "dmStatusFilter", targetNamespace = "http://isds.czechpoint.cz/v20")
        String dmStatusFilter,
        @WebParam(name = "dmOffset", targetNamespace = "http://isds.czechpoint.cz/v20")
        BigInteger dmOffset,
        @WebParam(name = "dmLimit", targetNamespace = "http://isds.czechpoint.cz/v20")
        BigInteger dmLimit,
        @WebParam(name = "dmRecords", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TRecordsArray> dmRecords,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

    /**
     * 
     * @param dmRecords
     * @param dmStatus
     * @param dmToTime
     * @param dmFromTime
     */
    @WebMethod(operationName = "GetMessageStateChanges")
    @RequestWrapper(localName = "GetMessageStateChanges", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TGetStateChangesInput")
    @ResponseWrapper(localName = "GetMessageStateChangesResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TGetStateChangesOutput")
    public void getMessageStateChanges(
        @WebParam(name = "dmFromTime", targetNamespace = "http://isds.czechpoint.cz/v20")
        XMLGregorianCalendar dmFromTime,
        @WebParam(name = "dmToTime", targetNamespace = "http://isds.czechpoint.cz/v20")
        XMLGregorianCalendar dmToTime,
        @WebParam(name = "dmRecords", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStateChangesArray> dmRecords,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

    /**
     * 
     * @param dmStatus
     * @param authorName
     * @param dmID
     * @param userType
     */
    @WebMethod(operationName = "GetMessageAuthor")
    @RequestWrapper(localName = "GetMessageAuthor", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TGetAuthorInput")
    @ResponseWrapper(localName = "GetMessageAuthorResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TGetAuthorOutput")
    public void getMessageAuthor(
        @WebParam(name = "dmID", targetNamespace = "http://isds.czechpoint.cz/v20")
        String dmID,
        @WebParam(name = "userType", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<String> userType,
        @WebParam(name = "authorName", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<String> authorName,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

    /**
     * 
     * @param dmIncoming
     * @param dmID
     * @return
     *     returns cz.czechpoint.isds.v20.TStatus
     */
    @WebMethod(operationName = "EraseMessage")
    @WebResult(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20")
    @RequestWrapper(localName = "EraseMessage", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TEraseMessageIntput")
    @ResponseWrapper(localName = "EraseMessageResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TEraseMessageOutput")
    public TStatus eraseMessage(
        @WebParam(name = "dmID", targetNamespace = "http://isds.czechpoint.cz/v20")
        String dmID,
        @WebParam(name = "dmIncoming", targetNamespace = "http://isds.czechpoint.cz/v20")
        boolean dmIncoming);

    /**
     * 
     * @param asyncID
     * @param dmToDate
     * @param dmStatus
     * @param dmOutFormat
     * @param dmFromDate
     * @param dmMonth
     * @param dmYear
     * @param dmMessageType
     */
    @WebMethod(operationName = "GetListOfErasedMessages")
    @RequestWrapper(localName = "GetListOfErasedMessages", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TGetListOfErasedInput")
    @ResponseWrapper(localName = "GetListOfErasedMessagesResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TGetListOfErasedOutput")
    public void getListOfErasedMessages(
        @WebParam(name = "dmFromDate", targetNamespace = "http://isds.czechpoint.cz/v20")
        XMLGregorianCalendar dmFromDate,
        @WebParam(name = "dmToDate", targetNamespace = "http://isds.czechpoint.cz/v20")
        XMLGregorianCalendar dmToDate,
        @WebParam(name = "dmYear", targetNamespace = "http://isds.czechpoint.cz/v20")
        BigInteger dmYear,
        @WebParam(name = "dmMonth", targetNamespace = "http://isds.czechpoint.cz/v20")
        BigInteger dmMonth,
        @WebParam(name = "dmMessageType", targetNamespace = "http://isds.czechpoint.cz/v20")
        String dmMessageType,
        @WebParam(name = "dmOutFormat", targetNamespace = "http://isds.czechpoint.cz/v20")
        String dmOutFormat,
        @WebParam(name = "asyncID", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<String> asyncID,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

    /**
     * 
     * @param asyncID
     * @param dmStatus
     * @param asyncReqType
     * @param asyncResponse
     */
    @WebMethod(operationName = "PickUpAsyncResponse")
    @RequestWrapper(localName = "PickUpAsyncResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TPickUpAsyncInput")
    @ResponseWrapper(localName = "PickUpAsyncResponseResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TPickUpAsyncOutput")
    public void pickUpAsyncResponse(
        @WebParam(name = "asyncID", targetNamespace = "http://isds.czechpoint.cz/v20")
        String asyncID,
        @WebParam(name = "asyncReqType", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.INOUT)
        Holder<String> asyncReqType,
        @WebParam(name = "asyncResponse", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<byte[]> asyncResponse,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

    /**
     * 
     * @param dmStatus
     * @param ntfScope
     * @param ntfRecords
     * @param ntfListContinues
     * @param ntfFromTime
     */
    @WebMethod(operationName = "GetListForNotifications")
    @RequestWrapper(localName = "GetListForNotifications", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TListForNotifInput")
    @ResponseWrapper(localName = "GetListForNotificationsResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TListForNotifOutput")
    public void getListForNotifications(
        @WebParam(name = "ntfFromTime", targetNamespace = "http://isds.czechpoint.cz/v20")
        XMLGregorianCalendar ntfFromTime,
        @WebParam(name = "ntfScope", targetNamespace = "http://isds.czechpoint.cz/v20")
        String ntfScope,
        @WebParam(name = "ntfRecords", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TNtfRecordsArray> ntfRecords,
        @WebParam(name = "ntfListContinues", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<Boolean> ntfListContinues,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

    /**
     * 
     * @param action
     * @return
     *     returns cz.czechpoint.isds.v20.TStatus
     */
    @WebMethod(operationName = "RegisterForNotifications")
    @WebResult(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20")
    @RequestWrapper(localName = "RegisterForNotifications", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.RegisterForNotifications")
    @ResponseWrapper(localName = "RegisterForNotificationsResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.RegisterForNotificationsResponse")
    public TStatus registerForNotifications(
        @WebParam(name = "action", targetNamespace = "http://isds.czechpoint.cz/v20")
        BigInteger action);

}
