
package cz.czechpoint.isds.v20;

import java.math.BigInteger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "dmInfoPortType", targetNamespace = "http://isds.czechpoint.cz/v20")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DmInfoPortType {


    /**
     * 
     * @param dmID
     * @param dmHash
     * @param dmStatus
     */
    @WebMethod(operationName = "VerifyMessage")
    @RequestWrapper(localName = "VerifyMessage", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TIDMessInput")
    @ResponseWrapper(localName = "VerifyMessageResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TMessageVerifyOutput")
    public void verifyMessage(
        @WebParam(name = "dmID", targetNamespace = "http://isds.czechpoint.cz/v20")
        String dmID,
        @WebParam(name = "dmHash", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<THash> dmHash,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

    /**
     * 
     * @param dmReturnedMessageEnvelope
     * @param dmID
     * @param dmStatus
     */
    @WebMethod(operationName = "MessageEnvelopeDownload")
    @RequestWrapper(localName = "MessageEnvelopeDownload", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TIDMessInput")
    @ResponseWrapper(localName = "MessageEnvelopeDownloadResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TMessEnvelDownOutput")
    public void messageEnvelopeDownload(
        @WebParam(name = "dmID", targetNamespace = "http://isds.czechpoint.cz/v20")
        String dmID,
        @WebParam(name = "dmReturnedMessageEnvelope", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TReturnedMessageEnvelope> dmReturnedMessageEnvelope,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

    /**
     * 
     * @param dmID
     * @return
     *     returns cz.czechpoint.isds.v20.TStatus
     */
    @WebMethod(operationName = "MarkMessageAsDownloaded")
    @WebResult(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20")
    @RequestWrapper(localName = "MarkMessageAsDownloaded", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TIDMessInput")
    @ResponseWrapper(localName = "MarkMessageAsDownloadedResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TMarkMessOutput")
    public TStatus markMessageAsDownloaded(
        @WebParam(name = "dmID", targetNamespace = "http://isds.czechpoint.cz/v20")
        String dmID);

    /**
     * 
     * @param dmDelivery
     * @param dmID
     * @param dmStatus
     */
    @WebMethod(operationName = "GetDeliveryInfo")
    @RequestWrapper(localName = "GetDeliveryInfo", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TIDMessInput")
    @ResponseWrapper(localName = "GetDeliveryInfoResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TDeliveryMessageOutput")
    public void getDeliveryInfo(
        @WebParam(name = "dmID", targetNamespace = "http://isds.czechpoint.cz/v20")
        String dmID,
        @WebParam(name = "dmDelivery", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TDelivery> dmDelivery,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

    /**
     * 
     * @param dmID
     * @param dmStatus
     * @param dmSignature
     */
    @WebMethod(operationName = "GetSignedDeliveryInfo")
    @RequestWrapper(localName = "GetSignedDeliveryInfo", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TIDMessInput")
    @ResponseWrapper(localName = "GetSignedDeliveryInfoResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TSignDelivMessOutput")
    public void getSignedDeliveryInfo(
        @WebParam(name = "dmID", targetNamespace = "http://isds.czechpoint.cz/v20")
        String dmID,
        @WebParam(name = "dmSignature", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<byte[]> dmSignature,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

    /**
     * 
     * @param dmFromTime
     * @param dmRecords
     * @param dmStatus
     * @param dmStatusFilter
     * @param dmLimit
     * @param dmToTime
     * @param dmOffset
     * @param dmSenderOrgUnitNum
     */
    @WebMethod(operationName = "GetListOfSentMessages")
    @RequestWrapper(localName = "GetListOfSentMessages", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TListOfSentInput")
    @ResponseWrapper(localName = "GetListOfSentMessagesResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TListOfMessOutput")
    public void getListOfSentMessages(
        @WebParam(name = "dmFromTime", targetNamespace = "http://isds.czechpoint.cz/v20")
        XMLGregorianCalendar dmFromTime,
        @WebParam(name = "dmToTime", targetNamespace = "http://isds.czechpoint.cz/v20")
        XMLGregorianCalendar dmToTime,
        @WebParam(name = "dmSenderOrgUnitNum", targetNamespace = "http://isds.czechpoint.cz/v20")
        BigInteger dmSenderOrgUnitNum,
        @WebParam(name = "dmStatusFilter", targetNamespace = "http://isds.czechpoint.cz/v20")
        String dmStatusFilter,
        @WebParam(name = "dmOffset", targetNamespace = "http://isds.czechpoint.cz/v20")
        BigInteger dmOffset,
        @WebParam(name = "dmLimit", targetNamespace = "http://isds.czechpoint.cz/v20")
        BigInteger dmLimit,
        @WebParam(name = "dmRecords", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TRecordsArray> dmRecords,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

    /**
     * 
     * @param dmFromTime
     * @param dmRecords
     * @param dmRecipientOrgUnitNum
     * @param dmStatus
     * @param dmStatusFilter
     * @param dmLimit
     * @param dmToTime
     * @param dmOffset
     */
    @WebMethod(operationName = "GetListOfReceivedMessages")
    @RequestWrapper(localName = "GetListOfReceivedMessages", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TListOfFReceivedInput")
    @ResponseWrapper(localName = "GetListOfReceivedMessagesResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TListOfMessOutput")
    public void getListOfReceivedMessages(
        @WebParam(name = "dmFromTime", targetNamespace = "http://isds.czechpoint.cz/v20")
        XMLGregorianCalendar dmFromTime,
        @WebParam(name = "dmToTime", targetNamespace = "http://isds.czechpoint.cz/v20")
        XMLGregorianCalendar dmToTime,
        @WebParam(name = "dmRecipientOrgUnitNum", targetNamespace = "http://isds.czechpoint.cz/v20")
        BigInteger dmRecipientOrgUnitNum,
        @WebParam(name = "dmStatusFilter", targetNamespace = "http://isds.czechpoint.cz/v20")
        String dmStatusFilter,
        @WebParam(name = "dmOffset", targetNamespace = "http://isds.czechpoint.cz/v20")
        BigInteger dmOffset,
        @WebParam(name = "dmLimit", targetNamespace = "http://isds.czechpoint.cz/v20")
        BigInteger dmLimit,
        @WebParam(name = "dmRecords", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TRecordsArray> dmRecords,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

    /**
     * 
     * @param dmID
     * @return
     *     returns cz.czechpoint.isds.v20.TStatus
     */
    @WebMethod(operationName = "ConfirmDelivery")
    @WebResult(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20")
    @RequestWrapper(localName = "ConfirmDelivery", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TIDMessInput")
    @ResponseWrapper(localName = "ConfirmDeliveryResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TConfirmDeliveryOutput")
    public TStatus confirmDelivery(
        @WebParam(name = "dmID", targetNamespace = "http://isds.czechpoint.cz/v20")
        String dmID);

    /**
     * 
     * @param dmFromTime
     * @param dmRecords
     * @param dmStatus
     * @param dmToTime
     */
    @WebMethod(operationName = "GetMessageStateChanges")
    @RequestWrapper(localName = "GetMessageStateChanges", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TGetStateChangesInput")
    @ResponseWrapper(localName = "GetMessageStateChangesResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TGetStateChangesOutput")
    public void getMessageStateChanges(
        @WebParam(name = "dmFromTime", targetNamespace = "http://isds.czechpoint.cz/v20")
        XMLGregorianCalendar dmFromTime,
        @WebParam(name = "dmToTime", targetNamespace = "http://isds.czechpoint.cz/v20")
        XMLGregorianCalendar dmToTime,
        @WebParam(name = "dmRecords", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStateChangesArray> dmRecords,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

    /**
     * 
     * @param dmID
     * @param authorName
     * @param dmStatus
     * @param userType
     */
    @WebMethod(operationName = "GetMessageAuthor")
    @RequestWrapper(localName = "GetMessageAuthor", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TGetAuthorInput")
    @ResponseWrapper(localName = "GetMessageAuthorResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TGetAuthorOutput")
    public void getMessageAuthor(
        @WebParam(name = "dmID", targetNamespace = "http://isds.czechpoint.cz/v20")
        String dmID,
        @WebParam(name = "userType", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<String> userType,
        @WebParam(name = "authorName", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<String> authorName,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

}
