
package cz.czechpoint.isds.v20;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "dmOperationsPortType", targetNamespace = "http://isds.czechpoint.cz/v20")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DmOperationsPortType {


    /**
     * 
     * @param dmID
     * @param dmStatus
     * @param dmFiles
     * @param dmEnvelope
     */
    @WebMethod(operationName = "CreateMessage")
    @RequestWrapper(localName = "CreateMessage", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TMessageCreateInput")
    @ResponseWrapper(localName = "CreateMessageResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TMessageCreateOutput")
    public void createMessage(
        @WebParam(name = "dmEnvelope", targetNamespace = "http://isds.czechpoint.cz/v20")
        cz.czechpoint.isds.v20.TMessageCreateInput.DmEnvelope dmEnvelope,
        @WebParam(name = "dmFiles", targetNamespace = "http://isds.czechpoint.cz/v20")
        TFilesArray dmFiles,
        @WebParam(name = "dmID", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<String> dmID,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

    /**
     * 
     * @param dmID
     * @param dmReturnedMessage
     * @param dmStatus
     */
    @WebMethod(operationName = "MessageDownload")
    @RequestWrapper(localName = "MessageDownload", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TIDMessInput")
    @ResponseWrapper(localName = "MessageDownloadResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TMessDownOutput")
    public void messageDownload(
        @WebParam(name = "dmID", targetNamespace = "http://isds.czechpoint.cz/v20")
        String dmID,
        @WebParam(name = "dmReturnedMessage", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TReturnedMessage> dmReturnedMessage,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

    /**
     * 
     * @param dmID
     * @param dmStatus
     * @param dmSignature
     */
    @WebMethod(operationName = "SignedMessageDownload")
    @RequestWrapper(localName = "SignedMessageDownload", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TIDMessInput")
    @ResponseWrapper(localName = "SignedMessageDownloadResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TSignedMessDownOutput")
    public void signedMessageDownload(
        @WebParam(name = "dmID", targetNamespace = "http://isds.czechpoint.cz/v20")
        String dmID,
        @WebParam(name = "dmSignature", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<byte[]> dmSignature,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

    /**
     * 
     * @param dmID
     * @param dmStatus
     * @param dmSignature
     */
    @WebMethod(operationName = "SignedSentMessageDownload")
    @RequestWrapper(localName = "SignedSentMessageDownload", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TIDMessInput")
    @ResponseWrapper(localName = "SignedSentMessageDownloadResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TSignedMessDownOutput")
    public void signedSentMessageDownload(
        @WebParam(name = "dmID", targetNamespace = "http://isds.czechpoint.cz/v20")
        String dmID,
        @WebParam(name = "dmSignature", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<byte[]> dmSignature,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

    /**
     * 
     * @param parameter
     */
    @WebMethod(operationName = "DummyOperation")
    @Oneway
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public void dummyOperation(
        @WebParam(name = "DummyOperation", targetNamespace = "http://isds.czechpoint.cz/v20", partName = "parameter")
        String parameter);

    /**
     * 
     * @param dmMultipleStatus
     * @param dmStatus
     * @param dmFiles
     * @param dmEnvelope
     * @param dmRecipients
     */
    @WebMethod(operationName = "CreateMultipleMessage")
    @RequestWrapper(localName = "CreateMultipleMessage", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TMultipleMessageCreateInput")
    @ResponseWrapper(localName = "CreateMultipleMessageResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TMultipleMessageCreateOutput")
    public void createMultipleMessage(
        @WebParam(name = "dmRecipients", targetNamespace = "http://isds.czechpoint.cz/v20")
        TMultipleMessageRecipients dmRecipients,
        @WebParam(name = "dmEnvelope", targetNamespace = "http://isds.czechpoint.cz/v20")
        cz.czechpoint.isds.v20.TMultipleMessageCreateInput.DmEnvelope dmEnvelope,
        @WebParam(name = "dmFiles", targetNamespace = "http://isds.czechpoint.cz/v20")
        TFilesArray dmFiles,
        @WebParam(name = "dmMultipleStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TMultipleStatus> dmMultipleStatus,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

    /**
     * 
     * @param dmStatus
     * @param dmMessage
     * @param dmAuthResult
     */
    @WebMethod(operationName = "AuthenticateMessage")
    @RequestWrapper(localName = "AuthenticateMessage", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TAuthenticateMessageInput")
    @ResponseWrapper(localName = "AuthenticateMessageResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TAuthenticateMessageOutput")
    public void authenticateMessage(
        @WebParam(name = "dmMessage", targetNamespace = "http://isds.czechpoint.cz/v20")
        byte[] dmMessage,
        @WebParam(name = "dmAuthResult", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<Boolean> dmAuthResult,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

}
