
package cz.czechpoint.isds.v20;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.jws.Oneway;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Holder;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * Eclipse Metro/3.0.2 (RELEASE-3.0.2-4d220c5; 2021-08-02T05:18:16+0000) JAXWS-RI/3.0.2 JAXWS-API/3.0.1 JAXB-RI/3.0.2 JAXB-API/${jaxb-api.version}
 * Generated source version: 3.0
 * 
 */
@WebService(name = "dmOperationsPortType", targetNamespace = "http://isds.czechpoint.cz/v20")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DmOperationsPortType {


    /**
     * 
     * @param dmStatus
     * @param dmFiles
     * @param dmEnvelope
     * @param dmID
     */
    @WebMethod(operationName = "CreateMessage")
    @RequestWrapper(localName = "CreateMessage", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TMessageCreateInput")
    @ResponseWrapper(localName = "CreateMessageResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TMessageCreateOutput")
    public void createMessage(
        @WebParam(name = "dmEnvelope", targetNamespace = "http://isds.czechpoint.cz/v20")
        cz.czechpoint.isds.v20.TMessageCreateInput.DmEnvelope dmEnvelope,
        @WebParam(name = "dmFiles", targetNamespace = "http://isds.czechpoint.cz/v20")
        TFilesArray dmFiles,
        @WebParam(name = "dmID", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<String> dmID,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

    /**
     * 
     * @param dmReturnedMessage
     * @param dmStatus
     * @param dmID
     */
    @WebMethod(operationName = "MessageDownload")
    @RequestWrapper(localName = "MessageDownload", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TIDMessInput")
    @ResponseWrapper(localName = "MessageDownloadResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TMessDownOutput")
    public void messageDownload(
        @WebParam(name = "dmID", targetNamespace = "http://isds.czechpoint.cz/v20")
        String dmID,
        @WebParam(name = "dmReturnedMessage", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TReturnedMessage> dmReturnedMessage,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

    /**
     * 
     * @param dmStatus
     * @param dmSignature
     * @param dmID
     */
    @WebMethod(operationName = "SignedMessageDownload")
    @RequestWrapper(localName = "SignedMessageDownload", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TIDMessInput")
    @ResponseWrapper(localName = "SignedMessageDownloadResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TSignedMessDownOutput")
    public void signedMessageDownload(
        @WebParam(name = "dmID", targetNamespace = "http://isds.czechpoint.cz/v20")
        String dmID,
        @WebParam(name = "dmSignature", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<byte[]> dmSignature,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

    /**
     * 
     * @param dmStatus
     * @param dmSignature
     * @param dmID
     */
    @WebMethod(operationName = "SignedSentMessageDownload")
    @RequestWrapper(localName = "SignedSentMessageDownload", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TIDMessInput")
    @ResponseWrapper(localName = "SignedSentMessageDownloadResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TSignedMessDownOutput")
    public void signedSentMessageDownload(
        @WebParam(name = "dmID", targetNamespace = "http://isds.czechpoint.cz/v20")
        String dmID,
        @WebParam(name = "dmSignature", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<byte[]> dmSignature,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

    /**
     * 
     * @param parameter
     */
    @WebMethod(operationName = "DummyOperation")
    @Oneway
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public void dummyOperation(
        @WebParam(name = "DummyOperation", targetNamespace = "http://isds.czechpoint.cz/v20", partName = "parameter")
        String parameter);

    /**
     * 
     * @param dmRecipients
     * @param dmMultipleStatus
     * @param dmStatus
     * @param dmFiles
     * @param dmEnvelope
     */
    @WebMethod(operationName = "CreateMultipleMessage")
    @RequestWrapper(localName = "CreateMultipleMessage", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TMultipleMessageCreateInput")
    @ResponseWrapper(localName = "CreateMultipleMessageResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TMultipleMessageCreateOutput")
    public void createMultipleMessage(
        @WebParam(name = "dmRecipients", targetNamespace = "http://isds.czechpoint.cz/v20")
        TMultipleMessageRecipients dmRecipients,
        @WebParam(name = "dmEnvelope", targetNamespace = "http://isds.czechpoint.cz/v20")
        cz.czechpoint.isds.v20.TMultipleMessageCreateInput.DmEnvelope dmEnvelope,
        @WebParam(name = "dmFiles", targetNamespace = "http://isds.czechpoint.cz/v20")
        TFilesArray dmFiles,
        @WebParam(name = "dmMultipleStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TMultipleStatus> dmMultipleStatus,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

    /**
     * 
     * @param dmMessage
     * @param dmStatus
     * @param dmAuthResult
     */
    @WebMethod(operationName = "AuthenticateMessage")
    @RequestWrapper(localName = "AuthenticateMessage", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TAuthenticateMessageInput")
    @ResponseWrapper(localName = "AuthenticateMessageResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TAuthenticateMessageOutput")
    public void authenticateMessage(
        @WebParam(name = "dmMessage", targetNamespace = "http://isds.czechpoint.cz/v20")
        byte[] dmMessage,
        @WebParam(name = "dmAuthResult", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<Boolean> dmAuthResult,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

    /**
     * 
     * @param dmValidTo
     * @param dmStatus
     * @param dmResultDoc
     * @param dmDoc
     */
    @WebMethod(operationName = "Re-signISDSDocument")
    @RequestWrapper(localName = "Re-signISDSDocument", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TResignDocInput")
    @ResponseWrapper(localName = "Re-signISDSDocumentResponse", targetNamespace = "http://isds.czechpoint.cz/v20", className = "cz.czechpoint.isds.v20.TResignDocOutput")
    public void reSignISDSDocument(
        @WebParam(name = "dmDoc", targetNamespace = "http://isds.czechpoint.cz/v20")
        byte[] dmDoc,
        @WebParam(name = "dmResultDoc", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<byte[]> dmResultDoc,
        @WebParam(name = "dmValidTo", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<XMLGregorianCalendar> dmValidTo,
        @WebParam(name = "dmStatus", targetNamespace = "http://isds.czechpoint.cz/v20", mode = WebParam.Mode.OUT)
        Holder<TStatus> dmStatus);

}
